name: Build Debian Package

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper devscripts build-essential
        
    - name: Build Debian package
      run: |
        chmod +x packages/debian/build-package.sh
        packages/debian/build-package.sh
        
    - name: List generated files
      run: ls -la
      
    - name: Upload package as artifact
      uses: actions/upload-artifact@v4
      with:
        name: cglass-devenv-deb
        path: "*.deb"
        retention-days: 30
